spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:nasa_challenge}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

asteral.nasa.api.key=Tq5oLVt0rqxkDeG8piS4bPc7qMDDzGtvNRCWfSgy
asteral.nasa.api.feed.endpoint=https://api.nasa.gov/neo/rest/v1/feed
asteral.nasa.api.details.endpoint=https://api.nasa.gov/neo/rest/v1/neo

# --- Caching Configuration ---
spring.cache.type=caffeine
spring.cache.cache-names=asteroid-feed,asteroid-details
spring.cache.caffeine.spec=expireAfterWrite=1h,maximumSize=100

# --- Resilience4j Circuit Breaker ---
resilience4j.circuitbreaker.instances.nasaApi.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.nasaApi.slidingWindowSize=10
resilience4j.circuitbreaker.instances.nasaApi.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.nasaApi.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.nasaApi.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.nasaApi.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.nasaApi.failureRateThreshold=50
resilience4j.circuitbreaker.instances.nasaApi.eventConsumerBufferSize=10

# --- Resilience4j Retry ---
resilience4j.retry.instances.nasaApi.maxAttempts=3
resilience4j.retry.instances.nasaApi.waitDuration=2s
resilience4j.retry.instances.nasaApi.retryExceptions=org.springframework.web.reactive.function.client.WebClientResponseException,java.io.IOException

# --- Actuator & Observability ---
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.probes.enabled=true

