CREATE TABLE suser (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(30) NOT NULL,
    CONSTRAINT uq_suser_username UNIQUE (username)
);

CREATE TABLE my_favorites (
    favorite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asteroid_reference_id VARCHAR(64) NOT NULL,
    username VARCHAR(50) NOT NULL,
    CONSTRAINT uq_favorite_user_asteroid UNIQUE (username, asteroid_reference_id),
    CONSTRAINT fk_favorite_username FOREIGN KEY (username) REFERENCES suser (username) ON DELETE CASCADE
);

CREATE INDEX idx_favorite_username ON my_favorites (username);
